sudo: required
services: 
  - docker

before_install:
  - docker build -t alanhouston/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true alanhouston/docker-react npm run test -- --coverage